export const restaurants = [
    {
        recipeId: 11,
        id: 1,
        image: require('../assets/restaurant2.jpeg'),
        title: 'Gayload Xpress',
        description: 'Fast Food',
        rating: '4.6',
        price: 'Rs 4500 for two',
        deliveryTime: '25 mins',
        offerDiscount1: '20% OFF',
        offerDiscount2: 'Up to Rs 100',
        proDiscount: 'PRO extra 20% OFF',
        maxSafety: 'Follows all Max Safety measures to ensure your food is safe',
    },
    {
        recipeId: 12,
        id: 2,
        image: require('../assets/restaurant3.jpeg'),
        title: 'Doon Darbar',
        description: 'North Indian, Mughlai',
        rating: '4.1',
        price: 'Rs 220 for one',
        deliveryTime: '28 mins',
        offerDiscount1: '40% OFF',
        offerDiscount2: 'Up to Rs 120',
        proDiscount: 'PRO extra 20% OFF',
        maxSafety: 'Follows all Max Safety measures to ensure your food is safe',
    },
    {
        recipeId: 13,
        id: 3,
        image: require('../assets/restaurant1.jpeg'),
        title: 'Walk In Woods',
        description: 'North Indian, Chinese, Fast Food',
        rating: '4.6',
        price: 'Rs 320 for two',
        deliveryTime: '32 mins',
        offerDiscount1: '50% OFF',
        offerDiscount2: 'Up to Rs 80',
        proDiscount: 'PRO extra 20% OFF',
        maxSafety: 'Follows all Max Safety measures to ensure your food is safe',
    },
    {
        recipeId: 14,
        id: 4,
        image: require('../assets/restaurant4.jpeg'),
        title: 'Rajdhani Chicken Point',
        description: 'North Indian, Mughlai',
        rating: '3.6',
        price: 'Rs 490 for two',
        deliveryTime: '29 mins',
        offerDiscount1: '250% OFF',
        offerDiscount2: 'Up to Rs 200',
        proDiscount: 'PRO extra 20% OFF',
        maxSafety: 'Follows all Max Safety measures to ensure your food is safe',
    },
    {
        recipeId: 15,
        id: 5,
        image: require('../assets/restaurant5.jpeg'),
        title: 'Uss Da Dhaba',
        description: 'North Indian',
        rating: '3.9',
        price: 'Rs 280 for two',
        deliveryTime: '23 mins',
        offerDiscount1: '10% OFF',
        offerDiscount2: 'Up to Rs 240',
        proDiscount: 'PRO extra 20% OFF',
        maxSafety: 'Follows all Max Safety measures to ensure your food is safe',
    },
    {
        recipeId: 11,
        id: 1,
        image: require('../assets/restaurant6.jpeg'),
        title: 'Waffles & Crepes',
        description: 'Fast Food',
        rating: '4.0',
        price: 'Rs 340 for two',
        deliveryTime: '32 mins',
        offerDiscount1: '70% OFF',
        offerDiscount2: 'Up to Rs 130',
        proDiscount: 'PRO extra 20% OFF',
        maxSafety: 'Follows all Max Safety measures to ensure your food is safe',
    },
    {
        recipeId: 12,
        id: 2,
        image: require('../assets/restaurant7.jpeg'),
        title: 'Subway',
        description: 'North Indian, Mughlai',
        rating: '4.5',
        price: 'Rs 500 for two',
        deliveryTime: '35 mins',
        offerDiscount1: '30% OFF',
        offerDiscount2: 'Up to Rs 220',
        proDiscount: 'PRO extra 20% OFF',
        maxSafety: 'Follows all Max Safety measures to ensure your food is safe',
    },
    {
        recipeId: 13,
        id: 3,
        image: require('../assets/restaurant8.jpeg'),
        title: 'Rustic Cafe & Restro',
        description: 'North Indian, Chinese, Fast Food',
        rating: '2.6',
        price: 'Rs 100 for one',
        deliveryTime: '27 mins',
        offerDiscount1: '30% OFF',
        offerDiscount2: 'Up to Rs 100',
        proDiscount: 'PRO extra 20% OFF',
        maxSafety: 'Follows all Max Safety measures to ensure your food is safe',
    },
    {
        recipeId: 14,
        id: 4,
        image: require('../assets/restaurant9.jpeg'),
        title: 'Aroma Restaurant',
        description: 'North Indian, Mughlai',
        rating: '3.8',
        price: 'Rs 180 for one',
        deliveryTime: '29 mins',
        offerDiscount1: '60% OFF',
        offerDiscount2: 'Up to Rs 130',
        proDiscount: 'PRO extra 20% OFF',
        maxSafety: 'Follows all Max Safety measures to ensure your food is safe',
    },
    {
        recipeId: 15,
        id: 5,
        image: require('../assets/restaurant10.jpeg'),
        title: 'Razzmatazz',
        description: 'North Indian',
        rating: '4.0',
        price: 'Rs 200 for one',
        deliveryTime: '31 mins',
        offerDiscount1: '560% OFF',
        offerDiscount2: 'Up to Rs 80',
        proDiscount: 'PRO extra 20% OFF',
        maxSafety: 'Follows all Max Safety measures to ensure your food is safe',
    },
];

export const category = [
        {
            name: 'MAX Safety',
            id: 1,
        },
        {
            name: 'Pro',
            id: 2,
        },
        {
            name: 'Cuisines',
            id: 3,
            icon: require('../assets/search.png'),
        },
        {
            name: 'Rating: 4.0+',
            id: 4,
        },
        {
            name: 'Fastest Delivery',
            id: 5,
        },
        {
            name: 'Offers',
            id: 6,
        },
        {
            name: 'Takeaway',
            id: 7,
        },
        {
            name: 'More',
            id: 8,
        },
];

export const dishesCategory = [
    {
        category: 'Healthy',
        id: 1,
        image: require('../assets/category2.jpeg'),
    },
    {
        category: 'Pizza',
        id: 2,
        image: require('../assets/category1.jpeg'),
    },
    {
        category: 'Burger',
        id: 3,
        image: require('../assets/category3.jpeg'),
    },
    {
        category: 'Chicken',
        id: 4,
        image: require('../assets/category4.jpeg'),
    },
    {
        category: 'Rolls',
        id: 5,
        image: require('../assets/category5.jpeg'),
    },
    {
        category: 'Biryani',
        id: 6,
        image: require('../assets/category6.jpeg'),
    },
    {
        category: 'Thali',
        id: 7,
        image: require('../assets/category7.jpeg'),
    },
    {
        category: 'Paneer',
        id: 8,
        image: require('../assets/category8.jpeg'),
    },
];